name: Keymap

options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: zh-Hans

settings:
  base:
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    MACOSX_DEPLOYMENT_TARGET: 14.0

targets:
  Keymap:
    type: application
    platform: macOS

    # 源文件目录
    sources:
      - path: Keymap/App
        group: App
      - path: Keymap/Core
        group: Core
      - path: Keymap/UI
        group: UI
      - path: Keymap/Models
        group: Models
      - path: Keymap/Data
        group: Data
      - path: Keymap/Utilities
        group: Utilities
      - path: Keymap/Resources
        group: Resources
        excludes:
          - "*.plist"

    # 配置文件
    settings:
      base:
        PRODUCT_NAME: Keymap
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.Keymap
        CODE_SIGN_ENTITLEMENTS: Keymap/Resources/Entitlements.plist
        INFOPLIST_FILE: Keymap/App/Info.plist
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/../Frameworks

      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      release:
        SWIFT_OPTIMIZATION_LEVEL: -O

    # Info.plist 配置
    info:
      path: Keymap/App/Info.plist
      properties:
        CFBundleDisplayName: Keymap
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHumanReadableCopyright: ""
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication

    # 依赖框架
    dependencies:
      - framework: Keymap/Resources/Entitlements.plist
        embed: false
      - sdk: Carbon.framework
      - sdk: ApplicationServices.framework

    # Scheme配置
    scheme:
      testTargets: []
      gatherCoverageData: false

    # 预编译脚本（可选）
    preBuildScripts: []

    # 后编译脚本（可选）
    postBuildScripts: []

# 项目级别配置
attributes:
  CLASSPREFIX: ""
  LastSwiftUpdateCheck: 1500
  LastUpgradeCheck: 1500

# 配置方案
configs:
  Debug: debug
  Release: release

schemes:
  Keymap:
    build:
      targets:
        Keymap: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
